export const EXAMPLE_REDUX_STORE = 'EXAMPLE_REDUX_STORE';

export const USUARIOS = {
  CREATE_USER: 'CREATE_USER',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAIL: 'CREATE_USER_FAIL',
};
