export const EXAMPLE_REDUX_STORE = 'EXAMPLE_REDUX_STORE';

export const USUARIOS = {
  CREATE_USER: 'CREATE_USER',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAIL: 'CREATE_USER_FAIL',
};

export const LOGIN = {
  LOGIN_ACCESS: 'LOGIN_ACCESS',
  LOGIN_ACCESS_SUCCESS: 'LOGIN_ACCESS_SUCCESS',
  LOGIN_ACCESS_FAIL: 'LOGIN_ACCESS_FAIL'
}
